service: survey

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  profile: personal
  apiKeys:
    - public-website
  environment:
    PGHOST: survey.cdqh2ydjbp8c.us-east-1.rds.amazonaws.com
    PGUSER: postgresmaster
    PGPASSWORD: X6KKbQeVoKBi
    PGDATABASE: surveydb

functions:
  createSurvey:
    handler: surveyHandlers.create
    events:
          - http:
              path: survey
              method: POST
              private: true
  getSurvey:
      handler: surveyHandlers.get
      events:
            - http:
                path: survey/{id}
                method: GET
                private: true
                cors: true
  createResponseForSurvey:
      handler: surveyResponseHandlers.create
      events:
            - http:
                path: survey/{id}/response
                method: POST
                private: true
                cors: true
  getAverageSurveyResponse:
        handler: surveyResponseHandlers.get
        events:
              - http:
                  path: survey/{id}/response
                  method: GET
                  private: true
                  cors: true

custom:
  webpackIncludeModules: true